spring.application.name=demo
# Enable H2 Console at /h2-console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:sellcoddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate will update the DB schema automatically based on your Entity classes
spring.jpa.hibernate.ddl-auto=update